"""Add filename field

Revision ID: cb33faaa65a0
Revises: b331b3d6d702
Create Date: 2022-04-24 21:33:02.669325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb33faaa65a0'
down_revision = 'b331b3d6d702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('filename', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'filename')
    # ### end Alembic commands ###
